<?php
namespace App\Repositories\Employee;

use App\Models\Employee;
use App\Repositories\BaseRepository;
use http\Env\Request;

class EmployeeRepository extends BaseRepository implements EmployeeRepositoryInterface
{
    public function getModel()
    {
        return Employee::class;
    }

    public function show($request)
    {
        //sort
        $sortDirection = $request->session()->get('sortDirection', 'asc');
        $sort = $request->get('sort','id');

        //search
        $team_id = $request->get('team_id');
        $name = $request->get('name');
        $email = $request->get('email');

        if($request->has('team_id')){
            $data = $this->model
                ->orderBy($sort,$sortDirection)
                ->where('team_id',$team_id)
                ->where('first_name','LIKE','%'.$name.'%')
                ->where('last_name','LIKE','%'.$name.'%')
                ->where('email','LIKE','%'.$email.'%')
                ->paginate(5);
        }else {
            $data = $this->model->orderBy($sort,$sortDirection)->paginate(config('constants.pagination_records'));
        }

        $sortDirection = $sortDirection == 'desc' ? 'asc': 'desc';

        $request->session()->put('sortDirection', $sortDirection);

        return $data;
    }

    public function create($attributes = [])
    {
        $attributes = $attributes->except([
            '_token',
            'submit',
        ]);;

        $attributes = array_merge($attributes, [
            'ins_id'=> session()->get('id_admin'),
            'ins_datetime' => date('Y-m-d H:i:s'),
        ]);
        return parent::create($attributes);
    }

    public function update($id, $attributes = [])
    {
        $attributes = $attributes->except([
            '_token',
            '_method',
            'submit',
        ]);

        $attributes = array_merge($attributes, [
            'upd_id'=> session()->get('id_admin'),
            'upd_datetime' => date('Y-m-d H:i:s'),
        ]);

        return parent::update($id, $attributes); // TODO: Change the autogenerated stub
    }

    public function softDelete($id)
    {
        $data = $this->model->find($id);

        if($data->del_flag == '0') {
            $data->update(['del_flag'=>'1']);
        }else {
            $data->delete($id);
        }
    }


}
